### ISSUE TITLE
1.2.18: Windows 11: Monero seed words: Unable to copy or paste when seed words are not visible

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/universe#2537]
**Describe the bug**
I have my Pin set:

- When I try to `copy` my Monero address and paste it, I am unable to. 
  - The `copy` icon updates to a `checkmark` but when I go to paste it, nothing happens
  - I was not prompted for a Pin entry
  - IF I first view my monero seed words & enter Pin and then copy and paste it works fine
  - I tried to see if the same occurs for the wallet `seed words` but that seems to work fine as I could copy and paste the seed words without first viewing them

**Pre-conditions:**
- User should have TU installed
- User should have TU open
- User should have set a Pin

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Wallet'
3. Scroll down to 'Monero Seed words'
4. Click on the `Copy` icon
5. Note I was not prompted for a Pin entry here
6. Confirm icon updates to `checkmark` to confirm seed words were copied
7. Go and try to paste the seed words by: `right click + paste` OR `ctrl + v`
8. Observe
**Expected behavior**
User should be able to copy and paste their Monero seed words without having to view them

**Screenshots**
If applicable, add screenshots to illustrate the problem.

**Desktop (please complete the following information):**
 - Aspire A315-59
 - Windows 11

**Additional context**
I noticed after I navigated away from the Wallet tab and came back, when I clicked on the `Copy` icon I was prompted for Pin and then was able to successfully copy and paste. On my first attempt I was not prompted for a Pin for either wallet seed words OR Monero seed words so I'll attach my logs:

[logs.zip](https://github.com/user-attachments/files/21231659/logs.zip)

**Comment by mmrrnn** [comment]
Fixed again here 😅 :
https://github.com/tari-project/universe/pull/2563/commits/a049e5e2a304ae414b09da1b0c5831799c0995e8

**Comment by Tas4tari** [comment]
@mmrrnn This is still occurring on Windows 11, app version 1.2.24.
When I have my Pin set , the first time, I click on `Copy` without viewing seed words, I am prompted for Pin and I am able to copy the Monero seed words successfully.
However ( I have not closed the Settings tab in this time), when I click on the `Copy` icon again, I am not prompted for the pin and the icon updates to the checkmark
When I go to paste the seed words it is empty

**Comment by brianp** [comment]
@shanimal08
