### ISSUE TITLE
1.5.0: Windows 11: Pin locking: Sync with Phone: When I go to `Sync with Phone` I am unable to as my Pin input modal is hidden behind the "Sync with Phone` modal

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/universe#2609]
**Describe the bug**
As a user I find that when I have Pin enabled and go to `Sync with Phone`, I am unable to get to the QR modal, because the Pin prompt modal is hidden behind the `Sync with Phone` modal

**Pre-conditions:**
- User should have TU installed
- User should have TU open
- User should have a Pin set

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Wallet'
3. Scroll down to and click on 'Sync with Phone'
4. Click on `I have the app`
5. Observe

**Expected behavior**
When user clicks on `I have the app`, they should see the pin prompt modal appear and they should be able to enter their pin

**Screenshots**

<img width="1246" height="861" alt="Image" src="https://github.com/user-attachments/assets/0df5d4eb-f41d-42cc-8471-b98041b3b2d6" />
<img width="1086" height="846" alt="Image" src="https://github.com/user-attachments/assets/2c3645bf-f3d0-461c-882f-a93f29f97156" />

**Desktop (please complete the following information):**
 - Aspire A315-59
 - Windows 11

**Comment by brianp** [comment]
This should be fixed in 1.5.3. Please verify.

**Comment by brianp** [comment]
@mmrrnn 😬 

Windows specific now.

**Comment by Tas4tari** [comment]
Tested on Windows 11, app version 1.5.4 and this is still an issue
