### ISSUE TITLE
Check sign on seed word redirect the user to import wallet

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/universe#960]
**Describe the bug**
When the user clicks on the reveal button on seed word, it redirect the user to the import wallet wallet process. I would rather say the user should get a pop up message informin them that it's the same wallet instead of going throuh the whole process.

**To Reproduce**
1. Go to wallet settings
2. Look at seed words
3. Click on the edit button
4. Select the check mark button
5. User gets redirected to the imprort wallet process 

**Expected behavior**
User shouldn't get a error message saying that the exsiting wallet.

**Video**
https://www.loom.com/share/8db833e5dd7945e3b3dcfb33bda42454?sid=7b042eac-0e36-4b73-b1d7-f87ca5ea7218

**Desktop (please complete the following information):**
 - OS & Version: MacBook Air 13 inch M1 2020 Sonoma 14.5
 - Browser & Version Testnet v0.5.51

**Comment by Tas4tari** [comment]
This is also occurring on Windows 11, app version 0.5.53

**Comment by Tas4tari** [comment]
Tested on Windows 11 on app version 0.5.58 and this is still an issue

**Comment by Tas4tari** [comment]
Tested on Windows 11 on app version 0.5.63 and this is still an issue

**Comment by Tas4tari** [comment]
Tested on Windows 11 on app version 0.6.2 and this is still an issue

**Comment by Tas4tari** [comment]
Tested on Windows 11 on app version 0.6.4 and this is still an issue. If I have clicked on the check mark without editing my seed words then there should be no change, and use should not go into the Import wallet state

**Comment by Tas4tari** [comment]
Tested on Windows 11, app version 0.6.14 and this is still an issue

**Comment by brianp** [comment]
This is interesting if any of @shanimal08 @BalazsSevecsek @mmrrnn @MCozhusheck want to take a look.

We should simply not do this if no change was made.
We should have a confirmation the user wants to abandon the current wallet, and import another.

**Comment by Tas4tari** [comment]
Tested on Windows 11, app version 0.6.17 and this is still an issue

**Comment by brianp** [comment]
Fixed in: https://github.com/tari-project/universe/pull/1070

**Comment by Anziskavds** [comment]
@brianp I just tested this on the MacBook Air 13 inch M1 2020 on Testnet v0.6.17 and it is still an issue. https://www.loom.com/share/8fb20503c40a4d44ab3b0833a4e79a46

**Comment by brianp** [comment]
0.6.17 was produced before this was merged

**Comment by Tas4tari** [comment]
Tested on Windows 11, app version 0.70 and this is no longer occurring
